// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC90S7f1OQRbMrEMtkvCqc3KazxNNnu3LE',
    appId: '1:764528743499:web:14cca2c72c537a5e9ca9ce',
    messagingSenderId: '764528743499',
    projectId: 'deiyar',
    authDomain: 'deiyar.firebaseapp.com',
    storageBucket: 'deiyar.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZWVcS6dVei-hP1zARe1yfx3joIWhl1_4',
    appId: '1:764528743499:android:31615e0c53d8e0d49ca9ce',
    messagingSenderId: '764528743499',
    projectId: 'deiyar',
    storageBucket: 'deiyar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqNzT5puy76-u-75KNbe5ySRJiPXtkaTI',
    appId: '1:764528743499:ios:7e417f84db13f4f19ca9ce',
    messagingSenderId: '764528743499',
    projectId: 'deiyar',
    storageBucket: 'deiyar.firebasestorage.app',
    iosBundleId: 'com.example.diyar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqNzT5puy76-u-75KNbe5ySRJiPXtkaTI',
    appId: '1:764528743499:ios:7e417f84db13f4f19ca9ce',
    messagingSenderId: '764528743499',
    projectId: 'deiyar',
    storageBucket: 'deiyar.firebasestorage.app',
    iosBundleId: 'com.example.diyar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC90S7f1OQRbMrEMtkvCqc3KazxNNnu3LE',
    appId: '1:764528743499:web:57b34a91cae578e69ca9ce',
    messagingSenderId: '764528743499',
    projectId: 'deiyar',
    authDomain: 'deiyar.firebaseapp.com',
    storageBucket: 'deiyar.firebasestorage.app',
  );

}